
export const ADDVACINES = "VACCINE.ADDVACCINESTOSTORE";

export const ADDHOSPITALS = "HOSPITAL.ADDHOSPITALSTOSTORE";
export const ADDCHARGE = "HOSPITAL.ADDCHARGE";

export const ADDUSER = "USER.ADDUSERTOSTORE";
export const SIGNOUT = "USER.SIGNOUTUSER";
export const SIGNIN = "USER.SIGNINUSER";

export const ADDAPPOINTMENTS = "APPOINTMENT.ADDAPPOINTMENTSTOSTORE";